#!/bin/bash
        ./gcovs SPEX_*.c spex_*.c 2>&1 | awk -f cov.awk | sort -n > cov.out
        sort -n cov.out > cov.sort
        ./covs > covs.out
        echo -n "statments not yet tested: "
        grep "#####" *.*.gcov | wc -l
        ./cover *.*.gcov > cover.out
