#!/bin/csh
# usage: dif directory files
echo '================================================================='
foreach file (*.?cov)
	echo $file
	grep "#####" $file
	echo '================================================================='
	end
