#!/bin/bash

# ------------------------------------------------------------------------------
# CHOLMOD/Tcov Module.  Copyright (C) 2005-2022, Timothy A. Davis.
# All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0+
# ------------------------------------------------------------------------------

# test coverage with the GPU enabled

make purge
make -j40

export CHOLMOD_USE_GPU=1
./ldemo ../../../Matrix/nd6k.mtx
./ldemo ../../../Matrix/nd6k_complex.mtx
./ldemo ../../../Matrix/nd6k_complex.mtx 1
./covall

export CHOLMOD_USE_GPU=0
./ldemo ../../../Matrix/nd6k.mtx
./ldemo ../../../Matrix/nd6k_complex.mtx
./ldemo ../../../Matrix/nd6k_complex.mtx 1
./covall

