#!/bin/csh

# ------------------------------------------------------------------------------
# CHOLMOD/Tcov Module.  Copyright (C) 2005-2022, Timothy A. Davis.
# All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0+
# ------------------------------------------------------------------------------

setenv CHOLMOD_USE_GPU 1
printenv
make
make gpu

unsetenv CHOLMOD_USE_GPU
printenv
make
make gpu

setenv CHOLMOD_USE_GPU 0
printenv
make
make gpu
