Mongoose_UserGuide.pdf: Mongoose_UserGuide.tex references.bib \
    Figures/BrotherlyMatching.eps \
    Figures/CommunityMatching.eps \
    Figures/MultilevelOverview.eps \
    title-info.tex Makefile
	xelatex Mongoose_UserGuide
	xelatex Mongoose_UserGuide
	bibtex Mongoose_UserGuide
	xelatex Mongoose_UserGuide
	xelatex Mongoose_UserGuide
