# ParU, Copyright (c) 2022-2024, Mohsen Aznaveh and Timothy A. Davis,
# All Rights Reserved.
# SPDX-License-Identifier: GPL-3.0-or-later

# remove all files not in the distribution, but keep
# the compiled paru mexFunction.
clean:
	- $(RM) -rf *.o

# remove all files not in the distribution
purge: clean
	- $(RM) -rf *.mex* 

