#!/bin/csh

foreach file ($argv[1-])
    echo "================================================================================"
    echo $file
    # cat -n $file | grep -B 5 -A 5 '#####' 
    cat -n $file | grep '#####' 
end
echo "================================================================================"
# echo "Total lines not covered:"
# cat $argv[1-] | grep "#####" | wc

