#!/bin/bash
# usage: cover files
# UMFPACK/Tcov/cover
# Copyright (c) 1995-2022, Timothy A. Davis.  All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0+
echo '================================================================='
for file in $@
do
        echo $file
        echo '================================================================='
        grep "#####" -A5 -B5 $file
        echo '================================================================='
done
