#!/bin/bash
# usage: gcovs files
# UMFPACK/Tcov/gcovs
# Copyright (c) 1995-2022, Timothy A. Davis.  All Rights Reserved.
# SPDX-License-Identifier: GPL-2.0+
echo '================================================================='
for file in $@
do
        gcov -fl $file
        echo '================================================================='
done
