#!/bin/bash
# CXSparse/Tcov/covall
# CXSparse, Copyright (c) 2006-2022, Timothy A. Davis. All Rights Reserved.
# SPDX-License-Identifier: LGPL-2.1+
        ./gcovs cs*.c |& awk -f cov.awk | sort -n > cov.out
        sort -n cov.out > cov.sort
        ./covs *.gcov > covs.out
        echo -n "statements not yet tested: "
        grep "#####" *gcov | wc -l
        ./cover *v > cover.out
