#!/bin/bash
# CXSparse/Tcov/covs
# CXSparse, Copyright (c) 2006-2022, Timothy A. Davis. All Rights Reserved.
# SPDX-License-Identifier: LGPL-2.1+
echo '================================================================='
for file in $@
do
        echo $file
        grep "#####" $file
        echo '================================================================='
done
