/* do not edit this file; generated by cholmod_make */
#undef log2
#include "../../metis-4.0/Lib/rename.h"
#undef log2
#define log2 METIS__log2
#include "mex.h"
#define malloc mxMalloc
#define free mxFree
#define calloc mxCalloc
#define realloc mxRealloc
