all:
	( cd CSparse ; $(MAKE) )
	( cd Test ; $(MAKE) )

clean:
	( cd CSparse ; $(MAKE) clean )
	( cd Test ; $(MAKE) clean )

purge:
	( cd CSparse ; $(MAKE) purge )
	( cd Test ; $(MAKE) purge )

distclean: purge

