#-------------------------------------------------------------------------------
# GraphBLAS/MATLAB/Makefile
#-------------------------------------------------------------------------------

# This Makefile is only intended to clean up the compiled files and files
# created by the gbmake.m function in MATLAB.  To compile GraphBLAS for use in
# MATLAB type 'gbmake' in MATLAB.

clean:
	$(RM) *.o *.obj

distclean: clean
	$(RM) *.mex* errlog.txt spok/*.mex* log.txt

purge: distclean

