#!/bin/sh

# SuiteSparse:GraphBLAS, Timothy A. Davis, (c) 2017-2023, All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

../build/simple_demo                   > simple_demo.out
../build/complex_demo                  > complex_demo_out.m
../build/complex_demo 1                > complex_demo_out2.m
../build/openmp_demo                   > openmp_demo.out

../build/import_demo < Matrix/west0067 > import_demo.out
../build/wildtype_demo                 > wildtype_demo.out

../build/gauss_demo > gauss_demo1.out
../build/gauss_demo > gauss_demo.out
exit 0
