#!/bin/bash
# usage: gcovs files
# CSparse/Tcov/gcovs
# Copyright (c) 2006-2022, Timothy A. Davis. All Rights Reserved.
# SPDX-License-Identifier: LGPL-2.1+
echo '================================================================='
for file in $@
do
        gcov -f $file
        echo '================================================================='
done
