function sandia = get_sandia_matrix_list
% return a list of matrices from Sandia

% selected Sandia matrices in UFcollection:
sandia = { ...
  'Sandia/oscil_dcop_01', ...
  'Sandia/oscil_dcop_57', ...
  'Sandia/oscil_trans_01', ...
  'Sandia/fpga_dcop_01', ...
  'Sandia/fpga_dcop_51', ...
  'Sandia/fpga_trans_01', ...
  'Sandia/fpga_trans_02', ...
  'Sandia/init_adder1', ...
  'Sandia/adder_dcop_01', ...
  'Sandia/adder_dcop_69', ...
  'Sandia/adder_trans_01', ...
  'Sandia/adder_trans_02', ...
  'Sandia/mult_dcop_01', ...
  'Sandia/mult_dcop_03' } ;

% sandia = { ...
%  '../matrices/oscil/dcop/matrix.001.mat', ...
%  '../matrices/oscil/dcop/matrix.057.mat', ...
%  '../matrices/oscil/trans/matrix.001.mat', ...
%  '../matrices/fpga/dcop/matrix.001.mat', ...
%  '../matrices/fpga/dcop/matrix.051.mat', ...
%  '../matrices/fpga/trans/matrix.001.mat', ...
%  '../matrices/fpga/trans/matrix.002.mat', ...
%  '../matrices/init_adder/add1.mat', ...
%  '../matrices/adder/dcop/matrix.001.mat', ...
%  '../matrices/adder/dcop/matrix.069.mat', ...
%  '../matrices/adder/trans/matrix.001.mat', ...
%  '../matrices/adder/trans/matrix.002.mat', ...
%  '../matrices/mult/dcop/matrix.001.mat', ...
%  '../matrices/mult/dcop/matrix.003.mat' } ;

% sandia = { ...
% '../matrices/oscil/dcop/matrix.001.mat', ...
% '../matrices/oscil/dcop/matrix.002.mat', ...
% '../matrices/oscil/dcop/matrix.003.mat', ...
% '../matrices/oscil/dcop/matrix.004.mat', ...
% '../matrices/oscil/dcop/matrix.005.mat', ...
% '../matrices/oscil/dcop/matrix.006.mat', ...
% '../matrices/oscil/dcop/matrix.007.mat', ...
% '../matrices/oscil/dcop/matrix.008.mat', ...
% '../matrices/oscil/dcop/matrix.009.mat', ...
% '../matrices/oscil/dcop/matrix.010.mat', ...
% '../matrices/oscil/dcop/matrix.011.mat', ...
% '../matrices/oscil/dcop/matrix.012.mat', ...
% '../matrices/oscil/dcop/matrix.013.mat', ...
% '../matrices/oscil/dcop/matrix.014.mat', ...
% '../matrices/oscil/dcop/matrix.015.mat', ...
% '../matrices/oscil/dcop/matrix.016.mat', ...
% '../matrices/oscil/dcop/matrix.017.mat', ...
% '../matrices/oscil/dcop/matrix.018.mat', ...
% '../matrices/oscil/dcop/matrix.019.mat', ...
% '../matrices/oscil/dcop/matrix.020.mat', ...
% '../matrices/oscil/dcop/matrix.021.mat', ...
% '../matrices/oscil/dcop/matrix.022.mat', ...
% '../matrices/oscil/dcop/matrix.023.mat', ...
% '../matrices/oscil/dcop/matrix.024.mat', ...
% '../matrices/oscil/dcop/matrix.025.mat', ...
% '../matrices/oscil/dcop/matrix.026.mat', ...
% '../matrices/oscil/dcop/matrix.027.mat', ...
% '../matrices/oscil/dcop/matrix.028.mat', ...
% '../matrices/oscil/dcop/matrix.029.mat', ...
% '../matrices/oscil/dcop/matrix.030.mat', ...
% '../matrices/oscil/dcop/matrix.031.mat', ...
% '../matrices/oscil/dcop/matrix.032.mat', ...
% '../matrices/oscil/dcop/matrix.033.mat', ...
% '../matrices/oscil/dcop/matrix.034.mat', ...
% '../matrices/oscil/dcop/matrix.035.mat', ...
% '../matrices/oscil/dcop/matrix.036.mat', ...
% '../matrices/oscil/dcop/matrix.037.mat', ...
% '../matrices/oscil/dcop/matrix.038.mat', ...
% '../matrices/oscil/dcop/matrix.039.mat', ...
% '../matrices/oscil/dcop/matrix.040.mat', ...
% '../matrices/oscil/dcop/matrix.041.mat', ...
% '../matrices/oscil/dcop/matrix.042.mat', ...
% '../matrices/oscil/dcop/matrix.043.mat', ...
% '../matrices/oscil/dcop/matrix.044.mat', ...
% '../matrices/oscil/dcop/matrix.045.mat', ...
% '../matrices/oscil/dcop/matrix.046.mat', ...
% '../matrices/oscil/dcop/matrix.047.mat', ...
% '../matrices/oscil/dcop/matrix.048.mat', ...
% '../matrices/oscil/dcop/matrix.049.mat', ...
% '../matrices/oscil/dcop/matrix.050.mat', ...
% '../matrices/oscil/dcop/matrix.051.mat', ...
% '../matrices/oscil/dcop/matrix.052.mat', ...
% '../matrices/oscil/dcop/matrix.053.mat', ...
% '../matrices/oscil/dcop/matrix.054.mat', ...
% '../matrices/oscil/dcop/matrix.055.mat', ...
% '../matrices/oscil/dcop/matrix.056.mat', ...
% '../matrices/oscil/dcop/matrix.057.mat', ...
% '../matrices/oscil/trans/matrix.001.mat', ...
% '../matrices/fpga/dcop/matrix.001.mat', ...
% '../matrices/fpga/dcop/matrix.002.mat', ...
% '../matrices/fpga/dcop/matrix.003.mat', ...
% '../matrices/fpga/dcop/matrix.004.mat', ...
% '../matrices/fpga/dcop/matrix.005.mat', ...
% '../matrices/fpga/dcop/matrix.006.mat', ...
% '../matrices/fpga/dcop/matrix.007.mat', ...
% '../matrices/fpga/dcop/matrix.008.mat', ...
% '../matrices/fpga/dcop/matrix.009.mat', ...
% '../matrices/fpga/dcop/matrix.010.mat', ...
% '../matrices/fpga/dcop/matrix.011.mat', ...
% '../matrices/fpga/dcop/matrix.012.mat', ...
% '../matrices/fpga/dcop/matrix.013.mat', ...
% '../matrices/fpga/dcop/matrix.014.mat', ...
% '../matrices/fpga/dcop/matrix.015.mat', ...
% '../matrices/fpga/dcop/matrix.016.mat', ...
% '../matrices/fpga/dcop/matrix.017.mat', ...
% '../matrices/fpga/dcop/matrix.018.mat', ...
% '../matrices/fpga/dcop/matrix.019.mat', ...
% '../matrices/fpga/dcop/matrix.020.mat', ...
% '../matrices/fpga/dcop/matrix.021.mat', ...
% '../matrices/fpga/dcop/matrix.022.mat', ...
% '../matrices/fpga/dcop/matrix.023.mat', ...
% '../matrices/fpga/dcop/matrix.024.mat', ...
% '../matrices/fpga/dcop/matrix.025.mat', ...
% '../matrices/fpga/dcop/matrix.026.mat', ...
% '../matrices/fpga/dcop/matrix.027.mat', ...
% '../matrices/fpga/dcop/matrix.028.mat', ...
% '../matrices/fpga/dcop/matrix.029.mat', ...
% '../matrices/fpga/dcop/matrix.030.mat', ...
% '../matrices/fpga/dcop/matrix.031.mat', ...
% '../matrices/fpga/dcop/matrix.032.mat', ...
% '../matrices/fpga/dcop/matrix.033.mat', ...
% '../matrices/fpga/dcop/matrix.034.mat', ...
% '../matrices/fpga/dcop/matrix.035.mat', ...
% '../matrices/fpga/dcop/matrix.036.mat', ...
% '../matrices/fpga/dcop/matrix.037.mat', ...
% '../matrices/fpga/dcop/matrix.038.mat', ...
% '../matrices/fpga/dcop/matrix.039.mat', ...
% '../matrices/fpga/dcop/matrix.040.mat', ...
% '../matrices/fpga/dcop/matrix.041.mat', ...
% '../matrices/fpga/dcop/matrix.042.mat', ...
% '../matrices/fpga/dcop/matrix.043.mat', ...
% '../matrices/fpga/dcop/matrix.044.mat', ...
% '../matrices/fpga/dcop/matrix.045.mat', ...
% '../matrices/fpga/dcop/matrix.046.mat', ...
% '../matrices/fpga/dcop/matrix.047.mat', ...
% '../matrices/fpga/dcop/matrix.048.mat', ...
% '../matrices/fpga/dcop/matrix.049.mat', ...
% '../matrices/fpga/dcop/matrix.050.mat', ...
% '../matrices/fpga/dcop/matrix.051.mat', ...
% '../matrices/fpga/trans/matrix.001.mat', ...
% '../matrices/fpga/trans/matrix.002.mat', ...
% '../matrices/init_adder/add1.mat', ...
% '../matrices/adder/dcop/matrix.001.mat', ...
% '../matrices/adder/dcop/matrix.002.mat', ...
% '../matrices/adder/dcop/matrix.003.mat', ...
% '../matrices/adder/dcop/matrix.004.mat', ...
% '../matrices/adder/dcop/matrix.005.mat', ...
% '../matrices/adder/dcop/matrix.006.mat', ...
% '../matrices/adder/dcop/matrix.007.mat', ...
% '../matrices/adder/dcop/matrix.008.mat', ...
% '../matrices/adder/dcop/matrix.009.mat', ...
% '../matrices/adder/dcop/matrix.010.mat', ...
% '../matrices/adder/dcop/matrix.011.mat', ...
% '../matrices/adder/dcop/matrix.012.mat', ...
% '../matrices/adder/dcop/matrix.013.mat', ...
% '../matrices/adder/dcop/matrix.014.mat', ...
% '../matrices/adder/dcop/matrix.015.mat', ...
% '../matrices/adder/dcop/matrix.016.mat', ...
% '../matrices/adder/dcop/matrix.017.mat', ...
% '../matrices/adder/dcop/matrix.018.mat', ...
% '../matrices/adder/dcop/matrix.019.mat', ...
% '../matrices/adder/dcop/matrix.020.mat', ...
% '../matrices/adder/dcop/matrix.021.mat', ...
% '../matrices/adder/dcop/matrix.022.mat', ...
% '../matrices/adder/dcop/matrix.023.mat', ...
% '../matrices/adder/dcop/matrix.024.mat', ...
% '../matrices/adder/dcop/matrix.025.mat', ...
% '../matrices/adder/dcop/matrix.026.mat', ...
% '../matrices/adder/dcop/matrix.027.mat', ...
% '../matrices/adder/dcop/matrix.028.mat', ...
% '../matrices/adder/dcop/matrix.029.mat', ...
% '../matrices/adder/dcop/matrix.030.mat', ...
% '../matrices/adder/dcop/matrix.031.mat', ...
% '../matrices/adder/dcop/matrix.032.mat', ...
% '../matrices/adder/dcop/matrix.033.mat', ...
% '../matrices/adder/dcop/matrix.034.mat', ...
% '../matrices/adder/dcop/matrix.035.mat', ...
% '../matrices/adder/dcop/matrix.036.mat', ...
% '../matrices/adder/dcop/matrix.037.mat', ...
% '../matrices/adder/dcop/matrix.038.mat', ...
% '../matrices/adder/dcop/matrix.039.mat', ...
% '../matrices/adder/dcop/matrix.040.mat', ...
% '../matrices/adder/dcop/matrix.041.mat', ...
% '../matrices/adder/dcop/matrix.042.mat', ...
% '../matrices/adder/dcop/matrix.043.mat', ...
% '../matrices/adder/dcop/matrix.044.mat', ...
% '../matrices/adder/dcop/matrix.045.mat', ...
% '../matrices/adder/dcop/matrix.046.mat', ...
% '../matrices/adder/dcop/matrix.047.mat', ...
% '../matrices/adder/dcop/matrix.048.mat', ...
% '../matrices/adder/dcop/matrix.049.mat', ...
% '../matrices/adder/dcop/matrix.050.mat', ...
% '../matrices/adder/dcop/matrix.051.mat', ...
% '../matrices/adder/dcop/matrix.052.mat', ...
% '../matrices/adder/dcop/matrix.053.mat', ...
% '../matrices/adder/dcop/matrix.054.mat', ...
% '../matrices/adder/dcop/matrix.055.mat', ...
% '../matrices/adder/dcop/matrix.056.mat', ...
% '../matrices/adder/dcop/matrix.057.mat', ...
% '../matrices/adder/dcop/matrix.058.mat', ...
% '../matrices/adder/dcop/matrix.059.mat', ...
% '../matrices/adder/dcop/matrix.060.mat', ...
% '../matrices/adder/dcop/matrix.061.mat', ...
% '../matrices/adder/dcop/matrix.062.mat', ...
% '../matrices/adder/dcop/matrix.063.mat', ...
% '../matrices/adder/dcop/matrix.064.mat', ...
% '../matrices/adder/dcop/matrix.065.mat', ...
% '../matrices/adder/dcop/matrix.066.mat', ...
% '../matrices/adder/dcop/matrix.067.mat', ...
% '../matrices/adder/dcop/matrix.068.mat', ...
% '../matrices/adder/dcop/matrix.069.mat', ...
% '../matrices/adder/trans/matrix.001.mat', ...
% '../matrices/adder/trans/matrix.002.mat', ...
% '../matrices/mult/dcop/matrix.001.mat', ...
% '../matrices/mult/dcop/matrix.002.mat', ...
% '../matrices/mult/dcop/matrix.003.mat' } ;
