#!/bin/csh

# 57 unique statements:
./klutest < ../Matrix/impcol_a.mtx

# 20:
./klutest < ../Matrix/GD99_cc.mtx

# 17:
./klutest < ../Matrix/two.mtx

# 10:
./klutest < ../Matrix/w156.mtx

# 3, xsize memgrow in klu_kernel
./klutest < ../Matrix/arrow.mtx

# 3, xsize memgrow in klu_kernel, 1 in klu_z_condest,
./klutest < ../Matrix/arrowc.mtx

# 2 in klu_z_kernel (if pivot == 0 and halt_if_singular, and in complex divide)
./klutest < ../Matrix/onec.mtx

# 1 in klu_kernel (if pivot == 0 and halt if singular)
./klutest < ../Matrix/one.mtx

# 1 in klu_z_condest:
./klutest < ../Matrix/1c.mtx

# 1 in klu_z_condest:
./klutest < ../Matrix/ctina.mtx
