#!/bin/csh

# 57 unique statements:
valgrind ./klutest < ../Matrix/impcol_a.mtx

# 20:
valgrind ./klutest < ../Matrix/GD99_cc.mtx

# 17:
valgrind ./klutest < ../Matrix/two.mtx

# 10:
valgrind ./klutest < ../Matrix/w156.mtx

# 3, xsize memgrow in klu_kernel
valgrind ./klutest < ../Matrix/arrow.mtx

# 3, xsize memgrow in klu_kernel, 1 in klu_z_condest,
valgrind ./klutest < ../Matrix/arrowc.mtx

# 2 in klu_z_kernel (if pivot == 0 and halt_if_singular, and in complex divide)
valgrind ./klutest < ../Matrix/onec.mtx

# 1 in klu_kernel (if pivot == 0 and halt if singular)
valgrind ./klutest < ../Matrix/one.mtx

# 1 in klu_z_condest:
valgrind ./klutest < ../Matrix/1c.mtx

# 1 in klu_z_condest:
valgrind ./klutest < ../Matrix/ctina.mtx
